### ISSUE TITLE
Dimensions and drawings for non scad users?

### ISSUE THREAD

**Issue by yongkimleng** [GliaX/Stethoscope#38]
I would like to make customizations/modifications to the design but not doing very well with SCAD (super slow for some reason). The STL gives errors while being imported into Solidworks, so I figure that it would be easier if I could re-design from scratch given the dimensions.
If it would be possible to also upload a pdf of drawing dimensions, it could help others as well :)

**Comment by tareko** [comment]
Hi @yongkimleng,

Thank you for this. I don't have the dimensions handy and I think we have to commit resources to other things at the moment. However, why not print one and grab a digital caliper to measure? That should get you most of the way there. Otherwise, we don't use or support any non-Free software tools in the project, so we can't really help with Solidworks.

Have you looked through the crystalCAD file? It should give you enough measurements to figure things out with a bit of work.

I'm going to close this issue as 'wontfix', but please feel free to comment further as desired. If you do end up making some drawings, please submit a PR to share them with others.

tarek : )

**Comment by yongkimleng** [comment]
I don't really have a printer, usually get my designs machined out of engineering plastic. I've been through like 2 different software which supposedly read scad files but they have been glitching out. Do let me know if anyone had success with something which works on Windows.

If someone in the community can grab a simple hand drawing, phone-captured photo of drawings or something, I can digitize it into a nice drawing too.
