### ISSUE TITLE
Ear tube & Y-piece outer diameter?

### ISSUE THREAD

**Issue by abitofalchemy** [GliaX/Stethoscope#41]
1. The tube connecting the eartube to the Y-pieace is called for it to be 20cm long in the list of materials, but if I look at the [sample in FB](https://www.facebook.com/photo.php?fbid=148469625666800&set=pb.100015112902901.-2207520000.1497223194.&type=3&theater) it looks shorter, is 20 cm is till the length to go with?
2. I had a really hard time with the outer diameter of ear-tubes and Y-piece  and the 4mm inner diameter/6mm OD tubing. It seems to me that this tubing should have a wider ID or the Y and ear-tubes be smaller in diameter. What do you think?  Look at the connecting points on my [current prototype](https://flic.kr/p/Vs68qJ)

**Comment by tareko** [comment]
Hi @abitofalchemy,

Congratulations on making the stethoscope! Regarding your questions:

1. Yes, 20cm is really the maximum. If you want to wear it around your neck, that may even end up being a bit short., since the decreased weight will not properly hold down the stethoscope and it will jut to the sides.
1. I strongly suggest the 4/6 and that is what we have tested with and is validated. However, if you want 6/8, there should theoretically be no deterioration.

It strikes me that it's possible you are using PVC and not Silicone tubing. PVC tubing has not been tested and it is unlikely that it will work. Is that perhaps why you're having such a hard time hooking it up?

**Comment by ajithmel** [comment]
that is very good and i like what you guys are doing, thank you
