### ISSUE TITLE
Spring is too tight when printed in PLA

### ISSUE THREAD

**Issue by tareko** [GliaX/Stethoscope#45]
The spring is too tight initially and needs significant softening to work properly.

**Comment by mrjohnc** [comment]
I loosened mine by softening the curved part of it in near boiling water for some seconds and then bending a little till it cooled, although this could be done too much and make the part useless. It seems important to get this right because PLA is the most commonly used printing material.

One suggestion would be to put some bends into the curved section to make it more springy, like how this spring works

https://www.youmagine.com/designs/parametric-spring

**Comment by sbamueller** [comment]
the spring is so tight its difficult to fit the ear pieces. I'm just trying with a 105% size, maybe this will help.

**Comment by tareko** [comment]
@sbamueller: Which model are you using? This should not be printed in PLA, and should be fine at this point. Could you post a screenshot of the STL you're using? Is it [this one](https://github.com/GliaX/Stethoscope/blob/master/source_files/stl/spring.stl)

**Comment by sbamueller** [comment]
last try was with 105%

![grafik](https://user-images.githubusercontent.com/24292608/75594639-ad231b80-5a89-11ea-8f75-fccb25ebc1cf.png)
with that it seems to work.

**Comment by tareko** [comment]
OK, great that you started from the 3mf!!!! Glad that it works. Sometimes indeed it needs a bit of scaling up or down..

**Comment by tareko** [comment]
I'm going to close this issue. re-open if anything remains.
