### ISSUE TITLE
ear plugs

### ISSUE THREAD

**Issue by sbamueller** [GliaX/Stethoscope#54]
I bought the xcessor ear plugs but those don't seem to fit with the ear tubes. Which type should I buy?

**Comment by tareko** [comment]
[These are the ones we use](https://www.amazon.ca/gp/product/B006VELFJY)! Sounds like you got the same. Could you post a short video / photo of the issue?

Also, not sure if you saw the [assembly video](https://glia.org/stethoscope), but it might be of help if you haven't?

**Comment by sbamueller** [comment]
[These are the one](https://www.amazon.de/gp/product/B07DJ58BJK/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)s I got from German Amazon. But I'm not really able to fit them around the IIIIII::::II 

Maybe its me?
I can fit the ones I still have from my MDF Stethoscope.

![A8F9BDAC-2204-433E-9DE8-5E8E171EB7E7_1_105_c](https://user-images.githubusercontent.com/24292608/75594138-0ab66880-5a88-11ea-8cba-9bd1ee950580.jpeg)

**Comment by tareko** [comment]
those look right. Two options:

1. What we do at glia is just exercise some patience and wrap it around. Once fitted, it sits well but can come undone, in which case crazy glue is routine for us.

2. You could take a file and file down the outer ring a bit so that the fit is smoother.

p.s., those prints look great.

**Comment by sbamueller** [comment]
I'll try that, thanks for your help
